import * as path from 'node:path';
import * as url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));

/** Repo root, resolved from this file rather than from `process.cwd()`. */
export const PACKAGE_ROOT = path.resolve(here, '..', '..');

/** Where the intentionally-failing specs and their config live. Deliberately
 *  outside `testDir`, so this package's own suite never collects them. */
export const REPORT_SRC_DIR = path.join(PACKAGE_ROOT, 'report-src');

/** Where the generated report lands. Wiped and regenerated by
 *  tests/global-setup.ts on every run, gitignored, never committed. */
export const REPORTS_DIR = path.join(PACKAGE_ROOT, '.tmp-reports');

/** The raw Playwright JSON report, straight from the real run. Tests that
 *  want a RunSummary read this path via this package's OWN local reader
 *  (src/report.ts's summaryFromReport) at assert time - see
 *  tests/support/failures.ts. No other package is involved. */
export const RAW_REPORT_PATH = path.join(REPORTS_DIR, 'report.json');

/** Absolute path to a scratch file inside the reports dir. */
export function scratchPath(name: string): string {
  return path.join(REPORTS_DIR, name);
}
